# Generated by Django 2.2.3 on 2019-07-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laudo_motor", "0002_auto_20190717_1143"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="laudomotor",
            options={"verbose_name_plural": "Laudos de Motor"},
        ),
        migrations.AlterField(
            model_name="laudomotor",
            name="cpf",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="laudomotor",
            name="estado_veiculo",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="laudomotor",
            name="marca",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="laudomotor",
            name="modelo",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="laudomotor",
            name="num_autorizacao",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="laudomotor",
            name="num_motor",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="laudomotor",
            name="tipo_servico",
            field=models.CharField(default="Gravação de Motor", max_length=25),
        ),
    ]
