# Generated by Django 2.2.3 on 2019-07-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laudo_chassi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="laudochassi",
            name="decalque",
            field=models.BooleanField(default=False),
        ),
    ]
