# Generated by Django 2.2.3 on 2019-07-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laudo_chassi", "0003_auto_20190716_2136"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="laudochassi",
            options={"verbose_name_plural": "Laudos de Chassi"},
        ),
        migrations.AlterField(
            model_name="laudochassi",
            name="ano_modelo",
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name="laudochassi",
            name="ano_veiculo",
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name="laudochassi",
            name="cpf",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="laudochassi",
            name="estado_veiculo",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="laudochassi",
            name="marca",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="laudochassi",
            name="modelo",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="laudochassi",
            name="num_autorizacao",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="laudochassi",
            name="num_chassi",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="laudochassi",
            name="tipo_servico",
            field=models.CharField(default="Gravação de Chassi", max_length=25),
        ),
    ]
