# Generated by Django 2.2.3 on 2019-07-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo_chassi', '0004_auto_20190723_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudochassi',
            name='ano_modelo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laudochassi',
            name='ano_veiculo',
            field=models.IntegerField(),
        ),
    ]
