# Generated by Django 2.2.3 on 2019-07-16 18:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaudoEtiqueta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_servico", models.CharField(default="Plaqueta", max_length=30)),
                ("num_chassi", models.CharField(default="Plaqueta", max_length=40)),
                (
                    "data_aplicacao",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "data_emissao",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("marca", models.CharField(blank=True, max_length=30)),
                ("modelo", models.CharField(blank=True, max_length=30)),
                ("ano_veiculo", models.IntegerField()),
                ("ano_modelo", models.IntegerField()),
                ("placa", models.CharField(blank=True, max_length=10)),
                ("cidade_veiculo", models.CharField(blank=True, max_length=30)),
                ("estado_veiculo", models.CharField(blank=True, max_length=30)),
                ("nome", models.CharField(blank=True, max_length=40)),
                ("cpf", models.CharField(blank=True, max_length=40)),
                (
                    "declaracao_de_servico",
                    models.TextField(
                        blank=True,
                        default="Declaramos que foi realizado o serviço de aplicação das Etiquetas de Identificação...",
                        max_length=300,
                    ),
                ),
                ("descricao_foto_1", models.CharField(blank=True, max_length=20)),
                ("foto_1", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("descricao_foto_2", models.CharField(blank=True, max_length=20)),
                ("foto_2", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("descricao_foto_3", models.CharField(blank=True, max_length=20)),
                ("foto_3", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("descricao_foto_4", models.CharField(blank=True, max_length=20)),
                ("foto_4", models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/")),
                ("indicacao", models.BooleanField(default=False)),
                ("valor_servico", models.IntegerField()),
            ],
        ),
    ]
