# Generated by Django 2.2.3 on 2019-07-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laudo_etiqueta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laudoetiqueta",
            name="num_chassi",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="laudoetiqueta",
            name="tipo_servico",
            field=models.CharField(default="Etiqueta", max_length=30),
        ),
    ]
