# Generated by Django 2.2.3 on 2019-07-16 00:54

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaudoPlaqueta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_controle", models.IntegerField(verbose_name=1012)),
                ("tipo_servico", models.CharField(default="Plaqueta", max_length=30)),
                (
                    "data_realizacao",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "data_emissao",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("responsavel", models.CharField(blank=True, max_length=40)),
                ("num_autorizacao", models.CharField(blank=True, max_length=30)),
                ("cidade_autorizacao", models.CharField(blank=True, max_length=30)),
                ("estado_autorizacao", models.CharField(blank=True, max_length=2)),
                ("marca", models.CharField(blank=True, max_length=30)),
                ("modelo", models.CharField(blank=True, max_length=30)),
                ("ano_veiculo", models.IntegerField(blank=True)),
                ("ano_modelo", models.IntegerField(blank=True)),
                ("placa", models.CharField(blank=True, max_length=10)),
                ("cidade_veiculo", models.CharField(blank=True, max_length=30)),
                ("estado_veiculo", models.CharField(blank=True, max_length=30)),
                ("nome", models.CharField(blank=True, max_length=40)),
                ("cpf", models.CharField(blank=True, max_length=40)),
                ("declaracao_de_servico", models.TextField(blank=True, max_length=300)),
                ("descricao_foto_1", models.CharField(blank=True, max_length=20)),
                ("foto_1", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("descricao_foto_2", models.CharField(blank=True, max_length=20)),
                ("foto_2", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("descricao_foto_3", models.CharField(blank=True, max_length=20)),
                ("foto_3", models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/")),
                ("indicacao", models.BooleanField(default=False)),
                ("valor_servico", models.IntegerField()),
            ],
        ),
    ]
