# Generated by Django 2.2.3 on 2019-07-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laudo_plaqueta", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laudoplaqueta",
            name="num_controle",
        ),
    ]
