# Generated by Django 2.2.3 on 2019-07-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laudo_plaqueta", "0004_auto_20190716_1411"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laudoplaqueta",
            name="num_controle",
        ),
    ]
